name: two_step
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3

  #Splash Screen
  flare_splash_screen: ^4.0.0

  #UI
  google_fonts: ^2.1.0

  #Color Generator
  palette_generator: ^0.3.0

  #Animations
  flutter_staggered_animations: ^1.0.0

  #State Management
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/splash/
   - assets/logo/
   - assets/shoes/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-w100.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-w200.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-w300.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-w400.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-w500.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-w600.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-w700.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-w800.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-w900.ttf
          weight: 900

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-w100.ttf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-w200.ttf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-w300.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-w400.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-w500.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-w600.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-w700.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-w800.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-w900.ttf
          weight: 900
