name: two_step
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #Splash Screen
  flare_splash_screen: ^3.0.1

  #UI
  google_fonts: ^1.1.0

  #Color Generator
  palette_generator: ^0.2.2

  #Animations
  flutter_staggered_animations: ^0.1.2

  #State Management
  provider: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/splash/
   - assets/logo/
   - assets/shoes/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-w100.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-w200.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-w300.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-w400.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-w500.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-w600.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-w700.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-w800.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-w900.ttf
          weight: 900

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-w100.ttf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-w200.ttf
          weight: 200
        - asset: assets/fonts/raleway/Raleway-w300.ttf
          weight: 300
        - asset: assets/fonts/raleway/Raleway-w400.ttf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-w500.ttf
          weight: 500
        - asset: assets/fonts/raleway/Raleway-w600.ttf
          weight: 600
        - asset: assets/fonts/raleway/Raleway-w700.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-w800.ttf
          weight: 800
        - asset: assets/fonts/raleway/Raleway-w900.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
